version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=meu_db
    networks:
      - app-network

  python-service:
    image: python-service:latest # Tive que adicionar a referência da imagem porque o stack deploy não suporta build
    deploy:
      replicas: 1
    depends_on:
      - db
    networks:
      - app-network

  api:
    image: python-service:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
    depends_on:
      - db
      - python-service
    networks:
      - app-network
    command: ["python", "app.py"]

networks:
  app-network:
    driver: overlay
