services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: meu_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  web:
    build: .
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

networks:
  app-network:
