services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: meu_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
    networks:
      - app-network

  python-service:
    build: ./app # Apontando para a pasta app
    networks:
      - app-network
    depends_on:
      - db

  api:
    build: ./app # Também usa a pasta app
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - db
      - python-service
    command: ["python", "app.py"]

networks:
  app-network:
