name: Deploy Docker App em VM Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Testar conexão SSH com netcat
        run: |
          echo "Testando conexão com porta 22..."
          nc -zv -w 5 ${{ secrets.SERVER_HOST }} 22 || echo " Falha na conexão com a porta 22 (SSH não acessível)"

      - name: Conectar com a VM e fazer o deploy
        uses: appleboy/ssh-action@v0.1.8

        with:
          host: ${{ secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.SERVER_USER }}/dataops-github-actions
            git pull origin main
            docker-compose down || true
            docker-compose up -d --build
