name: Deploy Docker App em VM Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy na VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ~/app
            git pull origin main
            docker build -t math-api .
            docker stop math-api || true
            docker rm math-api || true
            docker run -d \
              --name math-api \
              --network=host \
              -p 80:80 \
              math-api
            echo "✅ Deploy concluído! Acesse: http://${{ secrets.SERVER_HOST }}/docs"
