name: Deploy Docker App em VM Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Testar conexão SSH
        run: |
          echo "🛜 Testando conectividade básica..."
          nc -zv -w 5 ${{ secrets.SERVER_HOST }} 22 || {
            echo "❌ Falha na conexão SSH";
            exit 1;
          }

      - name: Deploy na VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.SERVER_USER }}/dataops-github-actions

            echo "🔄 Atualizando repositório..."
            git pull origin main

            echo "🐋 Reconstruindo containers..."
            docker compose build --no-cache && 
            docker compose down --remove-orphans &&
            docker compose up -d --force-recreate

            echo "✅ Deploy concluído!"
            docker compose ps
